### ISSUE TITLE
JEI Support

### ISSUE THREAD

**Issue by Vequinox** [TeamMetallurgy/Masonry#15]
Add support to JEI so players will know the smelting/stonecutting recipes. This may already be taken care of for us if JEI just looks for recipe files. Research needed.

**Comment by IronPiston** [comment]
[For what it is worth, this is an open issue on the JEI issue tracker](https://github.com/mezz/JustEnoughItems/issues/1774)

**Comment by GirafiStudios** [comment]
Both Smelting and Stonecutter recipes is showing up in JEI for 1.20.1
