### ISSUE TITLE
Item tag for masonry:stone is broken

### ISSUE THREAD

**Issue by WenXin20** [TeamMetallurgy/Masonry#19]
**Describe the bug**
The item tag for masonry:stone is broken, the log states that `masonry:stonecobbled` is an unknown value.

**To Reproduce**
1. Load a world up
2. Check the log for tags by searching for "item tag list"

**Expected behavior**
Tags should function properly.

**Version:**
 - Mod Version 0.3.1
 - Forge Version 28.1.109

**Additional context**
- If you want the blocks to have compatiblity with other mods, such as in recipes, there needs to be a stone tag in the forge folder in the path `data/forge/tags/blocks/stone.json` and in `data/forge/tags/items/stone.json` to define the block and it's corresponding item as stone or in the minecraft data folder for walls.

**Comment by Vequinox** [comment]
Thanks for bringing this up, I will give it a look soon and update accordingly.

**Comment by Vequinox** [comment]
@WenXin20 I just uploaded an updated version that will (hopefully) add those tags. Please give it a look and get back to me when you can. I'll close this issue in a few days if I hear nothing back by then.

**Comment by WenXin20** [comment]
Sure!

**Comment by WenXin20** [comment]
It looks like the newer version never was released? Sorry, I forgot to check earlier.

Also, walls should be in a tag called `#minecraft:walls` instead of `#forge:stone`, otherwise mod recipes would accept walls in their recipe instead of only accepting full stone blocks. And slabs have a tag called `#minecraft:slabs`

Also, could the item & block tag `#forge:supports_conduit` be added to prismarine blocks, slabs, & walls? This would allow all the prismarine to work with the Conduit.
