### ISSUE TITLE
This seemingly breaks Anvils; I'm unable to use them because the interface closes immediately after I open it

### ISSUE THREAD

**Issue by SeriousAmaro** [TeamMetallurgy/Masonry#20]
With the last release of Masonry on Twitch on the 11th of January 2020, the mods breaks anvils; they close as soon as you open them

**Comment by Gbergz** [comment]
I'll add onto this, the latest update seem to break things. Silent's Gems breaks with it, leaves are decaying all over the place & some other stuff broke too. I'll revert to the previous update until this is fixed.

**Comment by Vequinox** [comment]
The latest update just added forge tags to the blocks in the mod, so all the stone variants will still count as stone for whatever recipes need stone, etc. Can you describe in what ways Silent's Gems breaks with it, as well as what other breaking things you're experiencing? I'm unsure why the newest changes made would start breaking all that stuff, but I can look into it.

**Comment by noobanidus** [comment]
https://gist.github.com/noobanidus/2c049d06848682b20af28039874cedc0 is the error

Specifically there are a few tags which failed to load, including forge:stone, which results in that error, which results in a lot of chaotic destruction.

**Comment by Vequinox** [comment]
Interesting. Yes, please revert to 0.3.1 while I look into this. Perhaps some syntax is incorrect on my part.

**Comment by StrangeThistle** [comment]
A lot of chaotic destruction. That sounds right. When I updated to 0.3.2, I could not craft anything, see any recipes either in JEI or the vanilla Minecraft book, water behaved like air (but still looked like water), and my achievements were reset. Good luck in your hunt for the misplaced comma. If it had actually caused a crash we might have been able to point you to a place in the code to start looking.

**Comment by noobanidus** [comment]
a) Switch to data generators, b) you can probably find an offline JSON-linter that will go through all the files and check them and tell you where the errors are. Failing that, there are a number of online options.
