### ISSUE TITLE
Walls are tagged as minecraft:slabs [1.15.2]

### ISSUE THREAD

**Issue by 00-Steven** [TeamMetallurgy/Masonry#21]
**Describe the bug**
All Masonry walls are tagged as minecraft:slabs

**To Reproduce**
1. Look at what any Masonry wall is tagged as
2. See minecraft:slabs in the list of tags

**Expected behavior**
I expect walls to not be tagged as slabs, as vanilla walls are also not tagged as slabs.

**Version (please complete the following information):**\
 - Mod Version [masonry-1.15.2-0.3.4]
 - Forge Version [31.2.26]

**Comment by Vequinox** [comment]
Sorry for late response. This will be fixed in next update.

**Comment by GirafiStudios** [comment]
Fixed in https://github.com/TeamMetallurgy/Masonry/commit/dd072da77c3f730a6d3736c509f6f9fed563bee3
