### ISSUE TITLE
Recipe error causes chronic lag spikes (1.15.2)

### ISSUE THREAD

**Issue by MurricaMan** [TeamMetallurgy/Masonry#23]
**Describe the bug**
There is an error in what looks like recipe handling, the lag spikes cause complete freezes, with less than five seconds between spikes. Spike last anywhere from five to fifteen seconds. The error is towards the end of the attached log.

**To Reproduce**
1. Install Masonry
2. Load or create a world
3. Error

**Expected behavior**
The game runs smoothly.

**Version:**
 - Mod Version 0.3.4 (1.15.2)
 - Forge Version 31.2.36

**Additional context**
Removing Masonry fixes the problem completely.
[2020-12-06-1.log](https://github.com/TeamMetallurgy/Masonry/files/5657055/2020-12-06-1.log)
Mod list without Masonry:
![image](https://user-images.githubusercontent.com/67217996/101445104-e1681a00-38ee-11eb-879b-cc756429ab91.png)

**Comment by GirafiStudios** [comment]
Unable to reproduce
